services:
    site:
        container_name: 'iapetus11.me'
        build:
            context: '.'
        ports:
            - '7387:3000'
        volumes:
            - type: bind
              source: ./.env
              target: /iapetus11.me/.env
        init: true
