version: "3.7"
services:
  site:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    ports:
      - "7387:3000"
    volumes:
      - type: bind
        source: ./.env
        target: /iapetus11.me/.env
    init: true
